With process choice

diff --git a/local-deploy b/local-deploy
--- a/local-deploy
+++ b/local-deploy
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+trap "exit 1" TERM
+export TOP_PID=$$
+
 function editor() {
 	[ "$EDITOR" != "" ] && echo $EDITOR && return
 	which vi && return
@@ -7,7 +10,15 @@ function editor() {
 	which ed
 }
 
+function quit() {
+	kill -s TERM $TOP_PID
+}
+
 function download() {
+	if ! tsuru app-info -a $APP > /dev/null
+	then
+		quit
+	fi 
 	if [ "$1" != "" ]
 	then
 		ENVS=$1
@@ -17,21 +28,32 @@ function download() {
 		TEMPFILE=$(mktemp)
 		echo "# Check env variables bellow from tsuru to be copied to local" > $TEMPFILE
 		echo "" >> $TEMPFILE
-		tsuru app-run -o "env|sed \"s/\(^[^=]*=\)\(.*\)/export \1'\2'/\"" -a $APP >> $TEMPFILE
+		tsuru app-run -a $APP -o "env|sed \"s/\(^[^=]*=\)\(.*\)/export \1'\2'/\"" >> $TEMPFILE
 		$(editor) $TEMPFILE
 		ENVS=$(cat $TEMPFILE)
 	fi
 	echo "Wait while copying unit. It may take several minutes..." 
 	if ! tsuru app-run -oi "echo \"$ENVS\" > /home/ubuntu/.envs; sudo tar -czf - 2>/dev/null / | base64" -a $APP | base64 --decode | docker import - $DOCKER_IMG
 	then
-		echo "Error while downloading!"
-		exit 1
+		echo "Error while downloading!" > /dev/stderr
+		quit
 	fi
 	echo "Download done!"
 }
 
 function get_start_script() {
-	docker run -it --rm $DOCKER_IMG sed "s/^[^:]*: *//" /home/application/current/Procfile | tr -d "\r" | head -n1
+	PARSED_PROCFILE=$(docker run -it --rm $FOLDER_CMD $DOCKER_IMG cat /home/application/current/Procfile | tr -d "\r" | grep -E '^[a-zA-Z0-9\-]+:[ ]*([^ ].+)$')
+	if [ "$PROCESSNAME" == "" ]
+	then
+		echo "$PARSED_PROCFILE" | cut -f2- -d: | paste -sd"&" -
+	else
+		if ! echo "$PARSED_PROCFILE" | grep "^$PROCESSNAME:" > /dev/null 2>&1
+		then
+			echo "$PROCESSNAME not found" > /dev/stderr
+			quit
+		fi
+		echo "$PARSED_PROCFILE" | grep "^$PROCESSNAME:" | cut -f2- -d:
+	fi
 }
 
 function get_docker_envs() {
@@ -39,24 +61,25 @@ function get_docker_envs() {
 }
 
 function start(){
-	if [ -z "$(docker images $DOCKER_IMG -q)" ] 
+	if [ -z "$(docker images $DOCKER_IMG -q)" ]
 	then
 		echo "Downloading image..."
-		download "$1"
+		export COPY_ENV=1
+		download
 	fi
-	[ "$FOLDER" != "" ] && FOLDER_CMD="-v $FOLDER:/home/application/current"
+	[ "$FOLDER" != "" ] && export FOLDER_CMD="-v $FOLDER:/home/application/current"
 	eval docker run -it --rm $FOLDER_CMD -e PORT=8888 -e port=8888 -u ubuntu -w /home/application/current -p $PORT:8888 $DOCKER_IMG /bin/bash -lc  \"tail -f /dev/null \& source /home/ubuntu/.envs \&\& $(get_start_script)\"
 }
 
 function update() {
 	ENVS=$(get_docker_envs)
-	delete && start "$ENVS"
+	delete && download "$ENVS" && start
 }
 
 function delete() {
 	if [ -z "$(docker images $DOCKER_IMG -q)" ]
 	then
-		echo "Image not found"
+		echo "Image not found" > /dev/stderr
 	else
 		docker rmi $DOCKER_IMG:latest --force
 	fi
@@ -77,7 +100,9 @@ function main() {
 }
 
 function help() {
-	echo "Usage: tsuru $(basename $0) -a|--app <appname> [-p|--process <processname>] [-l|--local-folder <folderpath>] [-c|--copy-environment] [-P|--port <port|8888>]  [update | start | delete]"
+	echo "Usage: tsuru $(basename $0) start -a|--app <appname> [-p|--process <processname>] [-l|--local-folder <folderpath>] [-P|--port <port|8888>]"
+	echo "Usage: tsuru $(basename $0) update -a|--app <appname> [-p|--process <processname>] [-l|--local-folder <folderpath>] [-P|--port <port|8888>] [-c|--copy-environment]"
+	echo "Usage: tsuru $(basename $0) delete -a|--app <appname>"
 }
 
 unset FOLDER_CMD
@@ -119,8 +144,8 @@ do
 			MODE="$1" 
 		;;
 		*)
-			help
-			exit 1
+			help > /dev/stderr
+			quit
 		;;
 	esac
 	shift # past argument or value
@@ -128,14 +153,14 @@ done
 
 if ! which docker > /dev/null
 then
-	echo "Please install docker"
-	exit 1
+	echo "Please install docker" > /dev/stderr
+	quit
 fi
 
 if [ "$APP" == "" ] || [ "$MODE" == "" ]
 then
-	help
-	exit 1
+	help > /dev/stderr
+	quit
 fi
 
 main "$MODE"
